"""Add initial tables

Revision ID: 36283b8d94db
Revises: e7923eeb214d
Create Date: 2024-09-28 14:52:39.246994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a8b836a694e3'
down_revision: Union[str, None] = '36283b8d94db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividad', sa.Column('precio', sa.Integer(), nullable=False))
    op.alter_column('actividad', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('actividad_nombre_key', 'actividad', type_='unique')
    op.drop_constraint('actividad_entrenador_ID_entrenador_fkey', 'actividad_entrenador', type_='foreignkey')
    op.drop_constraint('actividad_entrenador_ID_actividad_fkey', 'actividad_entrenador', type_='foreignkey')
    op.create_foreign_key(None, 'actividad_entrenador', 'entrenador', ['ID_entrenador'], ['ID_entrenador'])
    op.create_foreign_key(None, 'actividad_entrenador', 'actividad', ['ID_actividad'], ['ID_actividad'])
    op.add_column('administrador', sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('cita', sa.Column('fecha', sa.Date(), nullable=False))
    op.add_column('cita', sa.Column('hora', sa.Time(), nullable=False))
    op.add_column('cita', sa.Column('duracion_minutos', sa.Integer(), nullable=False))
    op.add_column('cita', sa.Column('lugar', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('cita', sa.Column('ID_entrenador', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('cita', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'cita', 'entrenador', ['ID_entrenador'], ['ID_entrenador'], ondelete='CASCADE')
    op.add_column('cliente', sa.Column('peso', sa.Float(), nullable=False))
    op.add_column('cliente', sa.Column('altura', sa.Float(), nullable=False))
    op.add_column('compra_membresia', sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('compra_membresia', sa.Column('tipo_compra', sa.Boolean(), nullable=False))
    op.drop_constraint('entrenador_ID_admin_creador_fkey', 'entrenador', type_='foreignkey')
    op.drop_column('entrenador', 'ID_admin_creador')
    op.add_column('entrenamiento', sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('entrenamiento', sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('entrenamiento', 'detalles')
    op.add_column('membresia', sa.Column('descuento', sa.Float(), nullable=False))
    op.add_column('membresia', sa.Column('max_miembros', sa.Integer(), nullable=False))
    op.add_column('membresia', sa.Column('precio', sa.Integer(), nullable=False))
    op.add_column('membresia', sa.Column('duracion_meses', sa.Integer(), nullable=False))
    op.add_column('proveedor', sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('proveedor', sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('proveedor', sa.Column('correo', sa.String(), nullable=True))
    op.add_column('proveedor', sa.Column('producto', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'proveedor', ['correo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proveedor', type_='unique')
    op.drop_column('proveedor', 'producto')
    op.drop_column('proveedor', 'correo')
    op.drop_column('proveedor', 'direccion')
    op.drop_column('proveedor', 'telefono')
    op.drop_column('membresia', 'duracion_meses')
    op.drop_column('membresia', 'precio')
    op.drop_column('membresia', 'max_miembros')
    op.drop_column('membresia', 'descuento')
    op.add_column('entrenamiento', sa.Column('detalles', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('entrenamiento', 'descripcion')
    op.drop_column('entrenamiento', 'tipo')
    op.add_column('entrenador', sa.Column('ID_admin_creador', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('entrenador_ID_admin_creador_fkey', 'entrenador', 'administrador', ['ID_admin_creador'], ['ID_admin'], ondelete='SET NULL')
    op.drop_column('compra_membresia', 'tipo_compra')
    op.drop_column('compra_membresia', 'metodo_pago')
    op.drop_column('cliente', 'altura')
    op.drop_column('cliente', 'peso')
    op.drop_constraint(None, 'cita', type_='foreignkey')
    op.alter_column('cita', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cita', 'ID_entrenador')
    op.drop_column('cita', 'lugar')
    op.drop_column('cita', 'duracion_minutos')
    op.drop_column('cita', 'hora')
    op.drop_column('cita', 'fecha')
    op.drop_column('administrador', 'direccion')
    op.drop_constraint(None, 'actividad_entrenador', type_='foreignkey')
    op.drop_constraint(None, 'actividad_entrenador', type_='foreignkey')
    op.create_foreign_key('actividad_entrenador_ID_actividad_fkey', 'actividad_entrenador', 'actividad', ['ID_actividad'], ['ID_actividad'], ondelete='CASCADE')
    op.create_foreign_key('actividad_entrenador_ID_entrenador_fkey', 'actividad_entrenador', 'entrenador', ['ID_entrenador'], ['ID_entrenador'], ondelete='CASCADE')
    op.create_unique_constraint('actividad_nombre_key', 'actividad', ['nombre'])
    op.alter_column('actividad', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('actividad', 'precio')
    # ### end Alembic commands ###
