"""Add initial tables

Revision ID: c5fde8ffe258
Revises: c02367f31436
Create Date: 2024-11-07 19:56:28.596021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c5fde8ffe258'
down_revision: Union[str, None] = 'c02367f31436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividad_entrenador')
    op.add_column('actividad', sa.Column('fecha', sa.Date(), nullable=False))
    op.add_column('actividad', sa.Column('hora', sa.Time(), nullable=False))
    op.add_column('actividad', sa.Column('duracion_minutos', sa.Integer(), nullable=False))
    op.add_column('actividad', sa.Column('lugar', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('actividad', sa.Column('ID_entrenador', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'actividad', 'entrenador', ['ID_entrenador'], ['ID_entrenador'], ondelete='SET NULL')
    op.drop_constraint('cita_ID_entrenador_fkey', 'cita', type_='foreignkey')
    op.drop_column('cita', 'ID_entrenador')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cita', sa.Column('ID_entrenador', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('cita_ID_entrenador_fkey', 'cita', 'entrenador', ['ID_entrenador'], ['ID_entrenador'], ondelete='CASCADE')
    op.drop_constraint(None, 'actividad', type_='foreignkey')
    op.drop_column('actividad', 'ID_entrenador')
    op.drop_column('actividad', 'lugar')
    op.drop_column('actividad', 'duracion_minutos')
    op.drop_column('actividad', 'hora')
    op.drop_column('actividad', 'fecha')
    op.create_table('actividad_entrenador',
    sa.Column('ID_actividad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ID_entrenador', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modificado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ID_actividad'], ['actividad.ID_actividad'], name='actividad_entrenador_ID_actividad_fkey'),
    sa.ForeignKeyConstraint(['ID_entrenador'], ['entrenador.ID_entrenador'], name='actividad_entrenador_ID_entrenador_fkey'),
    sa.PrimaryKeyConstraint('ID_actividad', 'ID_entrenador', name='actividad_entrenador_pkey')
    )
    # ### end Alembic commands ###
