"""Add initial tables

Revision ID: d0295b52ada4
Revises: fd7dfa052c20
Create Date: 2024-09-28 18:01:04.338425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0295b52ada4'
down_revision: Union[str, None] = 'fd7dfa052c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actividad', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('actividad', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    op.add_column('actividad_entrenador', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('actividad_entrenador', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    op.add_column('cita', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('cita', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    op.add_column('cliente', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('cliente', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    op.add_column('compra_membresia', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('compra_membresia', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    op.add_column('entrenador', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('entrenador', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    op.add_column('entrenamiento', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('entrenamiento', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    op.add_column('membresia', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('membresia', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membresia', 'modificado_en')
    op.drop_column('membresia', 'creado_en')
    op.drop_column('entrenamiento', 'modificado_en')
    op.drop_column('entrenamiento', 'creado_en')
    op.drop_column('entrenador', 'modificado_en')
    op.drop_column('entrenador', 'creado_en')
    op.drop_column('compra_membresia', 'modificado_en')
    op.drop_column('compra_membresia', 'creado_en')
    op.drop_column('cliente', 'modificado_en')
    op.drop_column('cliente', 'creado_en')
    op.drop_column('cita', 'modificado_en')
    op.drop_column('cita', 'creado_en')
    op.drop_column('actividad_entrenador', 'modificado_en')
    op.drop_column('actividad_entrenador', 'creado_en')
    op.drop_column('actividad', 'modificado_en')
    op.drop_column('actividad', 'creado_en')
    # ### end Alembic commands ###
