"""Add initial tables

Revision ID: fbee286b3225
Revises: 0e5d0205a9dd
Create Date: 2024-11-07 22:06:41.094541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbee286b3225'
down_revision: Union[str, None] = '0e5d0205a9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrador', sa.Column('rango', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('cliente', sa.Column('rango', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('entrenador', sa.Column('rango', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrenador', 'rango')
    op.drop_column('cliente', 'rango')
    op.drop_column('administrador', 'rango')
    # ### end Alembic commands ###
