"""Add initial tables

Revision ID: fd7dfa052c20
Revises: f9cdd5d86569
Create Date: 2024-09-28 17:49:39.381185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7dfa052c20'
down_revision: Union[str, None] = 'f9cdd5d86569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrador', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('administrador', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    op.add_column('proveedor', sa.Column('creado_en', sa.DateTime(), nullable=False))
    op.add_column('proveedor', sa.Column('modificado_en', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedor', 'modificado_en')
    op.drop_column('proveedor', 'creado_en')
    op.drop_column('administrador', 'modificado_en')
    op.drop_column('administrador', 'creado_en')
    # ### end Alembic commands ###
